on:
  issue_comment:
    types: [created]

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_sha }}

      - uses: actions/cache@v2
        with:
          path: ./poison_ic
          key: poison_ic_key
      - run: |
          cat poison_ic
