name: debug

on:
  push:

jobs:
  enum:
    runs-on: ubuntu-latest
    steps:
      - id: dump
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          cat <<"EOF"
          ${{ toJSON(github.event) }}
          EOF
