name: Dispatch

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'
        required: true
        type: string

jobs:
  echo_trigger:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Echo trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          #cat << EOF
          #${{ toJSON(github.event) }}
          #EOF
          cat > payload.json << 'EOF'
          ${{ toJson(github.event) }}
          EOF
