name: Dispatch

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'
        required: true
        type: string

jobs:
  echo_trigger:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Echo trigger
        env:
          payload: |
            
            EOF
            whoami
            cat << EOF
            EOF
        run: |
          cat << EOF
          ${{ toJSON(env) }}
          EOF

