name: Dispatch

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'
        required: true
        type: string

jobs:
  echo_trigger:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: echo 'FOO ${{ toJSON(github.event) }}'
      - name: Echo trigger
        run: |
          cat > payload.json << 'EOF'
          ${{ toJson(github.event) }}
          EOF
          cat payload.json
