name: Enum

on:
  push:
  workflow_dispatch:

jobs:
  enum:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: |
            const owner = "pwntester";
            const repo = "octo.nvim";

            // Requires admin perms
            //const permissions = github.rest.actions.getGithubActionsDefaultWorkflowPermissionsRepository({
            //  owner,
            //  repo,
            //});
            //console.log(permissions);

            var results = [];

            const workflows = await github.rest.actions.listRepoWorkflows({
              owner,
              repo,
            });
            //console.log(workflows);

            if (workflows.data.workflows.total_count == 0) {
              console.log("No workflows found");
              return;
            }
            for (const workflow of workflows.data.workflows) {
              console.log("Workflow ID: " + workflow.id);
              console.log("Workflow Path: " + workflow.path);
              const runs = await github.rest.actions.listWorkflowRuns({
                "owner": owner,
                "repo": repo,
                "workflow_id": workflow.id,
                "status": "success"
              });   
              //console.log(runs);
              if (runs.data.total_count > 0) {
                const last_run = runs.data.workflow_runs[0];
                //console.log(last_run);

                const run_id = last_run.id;
                console.log("Last Run ID: " + run_id);
                const jobs = await github.rest.actions.listJobsForWorkflowRun({
                  owner,
                  repo,
                  run_id,
                });
                if (jobs.data.total_count > 0) {
                  const first_job = jobs.data.jobs[0]; 
                  console.log("Job ID: " + first_job.id);
                  const logs = await github.rest.actions.downloadJobLogsForWorkflowRun({
                    "owner": owner,
                    "repo": repo,
                    "job_id": first_job.id,
                  });

                  var permissions = {};
                  var runner = {};
                  var in_perm_lines = false;
                  var in_runner_lines = false;
                  var secret_source = "";
                  for (const line of logs.data.split("\n")) {
                    const parts = line.split(" ")
                    const msg = parts.slice(1).join(" ");
                    if (msg == "##[group]GITHUB_TOKEN Permissions") {
                      in_perm_lines = true;
                      in_runner_lines = false;
                    } else if (msg == "##[group]Runner Image") {
                      in_perm_lines = false;
                      in_runner_lines = true;
                    } else if (msg == "##[endgroup]") {
                      in_perm_lines = false;
                      in_runner_lines = false;
                    } else if (in_perm_lines) {
                      const [key, value] = msg.split(":");
                      permissions[key.trim()] = value.trim();
                    } else if (in_runner_lines) {
                      const [key, value] = msg.split(":");
                      runner[key.trim()] = value.trim();
                    } else if (msg.startsWith("Secret source:")) {
                      secret_source = msg.split(":")[1].trim();
                    }
                  }
                  results.push({
                    "path": workflow.path,
                    "permissions": permissions,
                    "runner": runner,
                    "secret_source": secret_source,
                  });

                }
              }
            }
            return results;
      - name: Get result
        run: echo "${{ toJSON(steps.set-result.outputs.result) }}"
  enum2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: test
        env: 
          PAYLOAD: "foo\nBAR=BAR"
          PAYLOAD2: "/bin/foo\n/bin/bar"
        run: |
          echo FOO=$(PAYLOAD) >> $GITHUB_ENV
          echo $PAYLOAD2 >> $GITHUB_PATH
      - run: |
          echo $FOO
          echo $BAR
          echo $PATH
