name: Enum

on:
  push:
  workflow_dispatch:

jobs:
  enum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: |
            const owner = "hashicorp";
            const repo = "terraform-provider-azurerm";

            // Requires admin perms
            //const permissions = github.rest.actions.getGithubActionsDefaultWorkflowPermissionsRepository({
            //  owner,
            //  repo,
            //});
            //console.log(permissions);

            const workflows = github.actions.listRepoWorkflows({
              owner,
              repo,
            });
            console.log(workflows);

            return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
