name: upload

on:
  workflow_dispatch:

jobs:
  enum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: |
            const owner = "hashicorp";
            const repo = "terraform-provider-azurerm";

            const workflows = await github.request(
              "GET /repos/{owner}/{repo}/actions/workflows",
              {
                owner: owner,
                repo: repo,
                headers: {
                  "X-GitHub-Api-Version": "2022-11-28",
                },
              },
            );

            if (runs.data.total_count == 0) {
              console.log("No workflos found");
              return;
            }

            for (const workflow of workflows) {
              const runs = await github.request(
                "GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs",
                {
                  owner: owner,
                  repo: repo,
                  workflow_id: workflow.id,
                  headers: {
                    "X-GitHub-Api-Version": "2022-11-28",
                  },
                },
              );

              if (runs.data.total_count == 0) {
                console.log("No runs found for workflow: " + workflow.name);
                continue;
              }
              const last_run = runs.data.workflow_runs[0];
              console.log(last_run);
            }

            return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
