name: Enum

on:
  workflow_dispatch:

jobs:
  enum:
    runs-on: ubuntu-latest
    steps:
      - id: enum
        uses: GitHubSecurityLab/workflow-enum-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # repo: "pwntester/octo.nvim"
      - name: Get result
        run: echo ${{ toJSON(steps.enum.outputs.data) }} | jq '.'
