name: Enum

on:
  push:
  workflow_dispatch:

jobs:
  enum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: |
            const owner = "pwntester";
            const repo = "octo.nvim";

            // Requires admin perms
            //const permissions = github.rest.actions.getGithubActionsDefaultWorkflowPermissionsRepository({
            //  owner,
            //  repo,
            //});
            //console.log(permissions);

            const workflows = await github.rest.actions.listRepoWorkflows({
              owner,
              repo,
            });
            //console.log(workflows);

            if (workflows.data.workflows.total_count == 0) {
              console.log("No workflows found");
              return;
            }
            for (const workflow of workflows.data.workflows) {
              const workflow_id = workflow.id;
              console.log("Workflow ID: " + workflow_id);
              const runs = await github.rest.actions.listWorkflowRuns({
                owner,
                repo,
                workflow_id,
              });   
              console.log(runs);
              if (runs.data.workflow_runs.total_count > 0) {
                const last_run = runs.data.workflow_runs[0];
                console.log(last_run);
              }
            }

            return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
