name: Event

on:
  push:
    branches-ignore: # Run the checks on all branches but the protected ones
      - master
      - release/*

  pull_request_target:
    branches:
      - main
      - release/*
    types:
      - opened
      - edited
      - reopened
      - ready_for_review

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Test 1 
        if: github.actor == 'torvalds' || github.actor == 'dependabot[bot]'
        run: echo "Test 1 should not be printed"
      - name: Test 2 
        if: |
          ${{ 
              github.actor == 'torvalds' || 
              github.actor == 'dependabot[bot]'
          }}
        run: echo "Test 2 should not be printed"
      - name: Test 3 
        if: ${{ github.actor == 'torvalds' || github.actor == 'dependabot[bot]' }}
        run: echo "Test 3 should not be printed"
      - name: Test 4 
        if:    ${{ github.actor == 'torvalds' || github.actor == 'dependabot[bot]' }}
        run: echo "Test 4 should not be printed"
      - name: Test 5 
        if: ${{ 
              github.actor == 'torvalds' || 
              github.actor == 'dependabot[bot]'
          }}
        run: echo "Test 5 should not be printed"
      - name: Test 6
        if: ${{ 
              github.actor == 'torvalds' || 
              github.actor == 'dependabot[bot]' }}
        run: echo "Test 6 should not be printed"
      - name: Test 7
        if: ${{ github.actor == 'torvalds' || github.actor == 'dependabot[bot]' }}
        run: echo "Test 7 should not be printed"
      - name: Test 8
        if: ${{ github.actor == 'torvalds' || github.actor == 'dependabot[bot]' }} ${{ always() }}
        run: echo "Test 8 should not be printed"
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - if: ${{ github.event_name == 'pull_request_target' }}
        run: |
          set -ex

          wc -l <<EOF
          ${{ toJSON(github.event) }}
          EOF

      - if: ${{ github.event_name == 'push' }}
        run: |
          set -ex

          wc -l  <<EOF
          ${{ toJSON(github.event) }}
          EOF
