name: Push
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          cat <<"EOF"
          ${{ toJSON(github.event) }}
          EOF
