name: Upload

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Create file
      run: |
        echo "FOO" > foo
    - name: Upload
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test_file
        path: .
