name: Upload

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Create file
      run: |
        echo "FOO" > artifact.txt
    - name: Upload
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: artifact
        path: ./artifact.txt
    - name: Adding markdown
      run: echo '### Hello <b>world</b><script>alert(document.domain)</script>! 🚀' >> $GITHUB_STEP_SUMMARY
